"""initial migration

Revision ID: 0332bd67ec09
Revises: 
Create Date: 2024-02-19 13:05:15.194630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0332bd67ec09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auctions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('starting_price', sa.Integer(), nullable=False),
    sa.Column('short_desc', sa.Text(), nullable=True),
    sa.Column('date_of_sale', sa.Date(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], name=op.f('fk_items_auction_id_auctions')),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_items_buyer_id_users')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_items_seller_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('auctions')
    # ### end Alembic commands ###
